/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_raditya_helloworldandroidjni_MainActivity */

#ifndef _Included_com_android_raditya_helloworldandroidjni_MainActivity
#define _Included_com_android_raditya_helloworldandroidjni_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_raditya_helloworldandroidjni_MainActivity
 * Method:    HelloNJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_android_raditya_helloworldandroidjni_MainActivity_HelloNJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
