/* DO NOT EDIT THIS FILE - it is machine generated */
#include "com_android_raditya_helloworldandroidjni_MainActivity.h"
/* Header for class com_android_raditya_helloworldandroidjni_MainActivity */

/*
 * Class:     com_android_raditya_helloworldandroidjni_MainActivity
 * Method:    HelloNJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_android_raditya_helloworldandroidjni_MainActivity_HelloNJNI
  (JNIEnv *env, jobject obj){
    (*env)->NewStringUTF(env, "Hello World!");
  }
